version: "3.8"
services:
  web:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
  test:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: pytest -vv
