// Generated by SwiftUI View Factory
struct GeneratedView: View {
  @State private var jsonInput: String = ""
  var body: some View {
    HStack {
      VStack {
        // id: statusDot
        Circle {
        }
        Spacer()
        // id: dropLabel
        Text("Drop Image Here")
        Spacer()
        // id: jsonInput
        TextField("Optional input", text: $jsonInput)
      }
      VStack {
        // id: previewDot
        Circle {
        }
        // id: codeLabel
        Text("Generated SwiftUI Code:")
        // id: codeBlock
        Text("// code preview here")
        // id: buildStatusBar
        Rectangle {
        }
      }
    }
  }
}
