/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    var body: some View {
        VStack {
            Text("Welcome Back")
                .foregroundColor(.gray)
            Button("Submit") { }
                .buttonStyle(.borderedProminent)
        }
    }
}
