// Generated by SwiftUI View Factory
struct GeneratedView: View {
  @State private var nameInput: String = ""
  @State private var emailInput: String = ""
  var body: some View {
    Form {
      // id: nameInput
      TextField("Name", text: $nameInput)
      // id: emailInput
      TextField("Email", text: $emailInput)
    }
  }
}
