/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    @State private var emailInput: String = ""
    var body: some View {
        TextField("Email", text: $emailInput)
    }
}
