/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    var body: some View {
        ScrollView {
            Text("Item 1")
            Text("Item 2")
            Text("Item 3")
        }
    }
}
