/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    var body: some View {
        ZStack {
            Image("background")
            Text("Overlay")
        }
    }
}
