/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    var userIsLoggedIn: Bool = false

    var body: some View {
        if userIsLoggedIn {
            Text("Welcome back!")
        } else {
            Button("Log in") { }
        }
    }
}
