/// Auto-generated by SwiftUI View Factory

import SwiftUI

struct GeneratedView: View {
    var body: some View {
        NavigationStack {
            List {
                Text("Row1")
            }
        }
    }
}
