// Generated by SwiftUI View Factory
import SwiftUI

struct GeneratedView: View {
  var body: some View {
    // id: root
    VStack {
      Text("Welcome")
      Image("logo")
      Button("Get Started") {}.buttonStyle(.borderedProminent)
    }
  }
}
