// Generated by SwiftUI View Factory
import SwiftUI
struct GeneratedView: View {
  var body: some View {
    HStack(spacing: 20) {
      // id: leftScreen
      VStack(spacing: 20) {
        // id: header
        HStack(spacing: 20) {
          Image("")
          Spacer()
          Image("")
        }
        Spacer()
        // id: contentArea
        Spacer()
        // id: footer
        HStack(spacing: 20) {
          TextField("", text: $textField)
          Text("|")
        }
      }
      // id: rightScreen
      VStack(spacing: 20) {
        // id: header
        HStack(spacing: 20) {
          Image("")
          Spacer()
          Image("")
        }
        Spacer()
        // id: contentArea
        VStack(spacing: 20) {
          Image("")
          // id: buttonRow
          HStack(spacing: 20) {
            Image("")
            Image("")
          }
          Image("")
        }
        Spacer()
        // id: footer
        HStack(spacing: 20) {
          TextField("", text: $textField)
          Text("|")
        }
      }
    }
  }
}
