name: Verify OpenAPI endpoint
goal: |
  Ensure the FastAPI service returns a valid OpenAPI schema from /openapi.json using Docker and HTTP.

steps:
  - name: Start the FastAPI service
    run: docker compose up -d fastapi-app

  - name: Wait for service to be ready
    run: |
      for i in {1..10}; do
        curl -sf http://localhost:8000/openapi.json && break
        sleep 1
      done

  - name: Validate OpenAPI schema via HTTP
    run: |
      curl -s http://localhost:8000/openapi.json | jq '.openapi' | grep -q '"3.'

  - name: Stop the FastAPI service
    run: docker compose down
