name: Validate OpenAPI schema via HTTP
goal: |
  Ensure the FastAPI server is running and exposes a valid OpenAPI schema at /openapi.json.
steps:
  - name: Start server in background
    run: uvicorn app.main:app --port 8000 &

  - name: Wait briefly to ensure server is up
    run: sleep 2

  - name: Fetch and validate schema
    run: |
      import requests
      resp = requests.get("http://localhost:8000/openapi.json")
      if resp.status_code != 200:
          print(f"❌ Status {resp.status_code}")
          print(resp.text)
          exit(1)
      data = resp.json()
      if "openapi" not in data:
          print("❌ Missing OpenAPI key in response")
          exit(1)
      print("✅ Valid OpenAPI schema found")
