name: Validate OpenAPI schema
goal: |
  Launch the FastAPI service using uvicorn and validate its /openapi.json response externally using requests.
steps:
  - name: Start FastAPI with uvicorn
    run: uvicorn app.main:app --port 8000 &

  - name: Wait for service to be ready
    run: sleep 2  # Allow server to start

  - name: Validate OpenAPI response
    run: |
      import requests
      try:
          resp = requests.get("http://localhost:8000/openapi.json")
          print("Status:", resp.status_code)
          print("Body:", resp.text)
          resp.raise_for_status()
          assert "openapi" in resp.json()
          print("✅ OpenAPI schema is valid")
      except Exception as e:
          print("❌ Failed:", e)
          raise SystemExit(1)
