name: Debug OpenAPI schema availability
goal: |
  Enhance the test to print debug information when the OpenAPI validation fails.
steps:
  - name: Ensure FastAPI service is importable
    run: |
      from fastapi.testclient import TestClient
      from app.main import app
      client = TestClient(app)
      resp = client.get('/openapi.json')

      if resp.status_code != 200:
          print("❌ Unexpected status:", resp.status_code)
          print("Response text:", resp.text)
      else:
          print("✅ Status OK")

      try:
          data = resp.json()
          if 'openapi' not in data:
              print("❌ No 'openapi' key in response")
              print("Response JSON:", data)
          else:
              print("✅ OpenAPI schema key found")
      except Exception as e:
          print("❌ Failed to parse JSON:", str(e))

      assert resp.status_code == 200
      assert 'openapi' in resp.json()
