name: Build Views
on:
  workflow_dispatch:
    inputs:
      upload_dir:
        description: 'Directory containing input MockViews'
        required: false
        default: 'upload'
      download_dir:
        description: 'Directory for generated SwiftUI views'
        required: false
        default: 'download'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Start API server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          echo $! > uvicorn.pid
          for i in {1..10}; do
            if curl -sf http://localhost:8000/secret > /dev/null; then
              break
            fi
            sleep 2
          done
      - name: Generate SwiftUI views via API
        run: |
          python scripts/build_views.py \
            --upload "${{ github.event.inputs.upload_dir }}" \
            --download "${{ github.event.inputs.download_dir }}"
      - name: Stop API server
        if: always()
        run: |
          kill $(cat uvicorn.pid)
      - name: Upload generated views
        uses: actions/upload-artifact@v4
        with:
          name: swiftui-views
          path: ${{ github.event.inputs.download_dir }}
