name: Test Hetzner Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:
      - name: ✅ Runner confirmed
        run: |
          echo "Hostname: $(hostname)"
          echo "Runner is alive and picked up this job."
