name: Test Hetzner Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:
      - name: Show runner info
        run: |
          echo "✅ Hostname: $(hostname)"
          echo "✅ Runner is working fine"
