name: Verify Hetzner Runner (FountainAI)

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted  # ✅ This matches your runner's actual label
    steps:
      - name: Confirm Runner Identity
        run: |
          echo "🔥 Running on: $(hostname)"
          echo "✅ Kernel: $(uname -a)"
          echo "🛠 Docker version:"
          docker version || echo "🚨 Docker NOT working"
          echo "🧪 Docker Compose version:"
          docker compose version || echo "🚨 Compose NOT working"
