name: Verify Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: self-hosted
    steps:
      - name: Check Environment
        run: |
          echo "Runner: $(hostname)"
          uname -a
          docker version
          docker compose version
